### ISSUE TITLE
Reliable Topic documentation problems

### ISSUE THREAD

**Issue by sancar** [hazelcast/hazelcast-reference-manual#114]
I have found problems with Reliable Topic related documentation.

1) http://docs.hazelcast.org/docs/3.6-EA3/manual/html-single/index.html#hazelcast-clients-feature-comparison
Here in the table, java client should change to yes. 

2) Programmatic configuration also is not correct

```
Config config = new Config();
ReliableTopicConfig rtConfig = config.getReliableTopicConfig();
rtConfig.setTopicOverloadPolicy( TopicOverloadPolicy.BLOCK )  <== Not string but over TopicOverloadPolicy
        .setReadBatchSize( 10 )
        .setStatisticsEnabled( true );                <==== without quotes
```

3) http://docs.hazelcast.org/docs/latest-dev/manual/html-single/index.html#sample-reliable-itopic-code
The explanation that comes after the code is not straightforward. There is relation between RingBuffer and ReliableTopic. One needs to configure RingBuffer to use some features of ReliableTopic. I think this one needs one more code in reference manual, or in code-samples.

4) As far as I understand, when using the ReliableTopic from client, user needs to configure RingBuffer one server side. This also needs more explanation. 

5) There are slight changes on client side configuration. `setStatisticsEnabled` is not available on client side. And config class name is different. => `ClientReliableTopicConfig`

I am not sure if I understand the whole RingBuffer & ReliableTopic relation. And if there might be more differences between server and client config. 

@pveentjer can help more here to update the reference-manual properly.

**Comment by Serdaro** [comment]
Thank you @sancar

**Comment by Serdaro** [comment]
@pveentjer , Could you please assist on the items 3, 4, and 5 above?

**Comment by Serdaro** [comment]
@pveentjer , still waiting for some comments on this one.

**Comment by Serdaro** [comment]
The clarifications can be found both at https://github.com/hazelcast/hazelcast-code-samples/tree/master/distributed-topic/reliable-topic and http://docs.hazelcast.org/docs/latest-dev/manual/html-single/#configuring-reliable-topic-at-client-side
