### ISSUE TITLE
Anchor links on the sidebar

### ISSUE THREAD

**Issue by gAmUssA** [hazelcast/hazelcast-reference-manual#125]
Hi,

in our current documentation website, sidebar contains a full link like 

`http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#hot-restart-persistence`

including website link + anchor which triggers a page reload each time (and because we switched to 1 file manual it takes some time) when one clicks on the link on the sidebar.

We should use approach with anchors only like here http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

**Comment by alparslanavci** [comment]
+1

**Comment by Serdaro** [comment]
Solved with the latest improvements. Please see http://docs.hazelcast.org/docs/latest-dev/manual/html-single/
