### ISSUE TITLE
Discovery SPI is also supported for Java Client.

### ISSUE THREAD

**Issue by Serdaro** [hazelcast/hazelcast-reference-manual#127]
Add content accordingly.

**Comment by bwzhang2011** [comment]
+1

**Comment by noctarius** [comment]
Well the implementation guide mentions Hazelcast clients as runtime targets (http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#discoveryservice-framework-integration) however yeah it should be mentioned on the non-extending part more obviously :+1:

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/9e32e16b5286f63a551c14f090c93605e95a0610
