### ISSUE TITLE
Map clear does not fire entryRemoved event

### ISSUE THREAD

**Issue by alparslanavci** [hazelcast/hazelcast-reference-manual#150]
When `IMap.clear()` method is called, we does not fire entryRemoved event. I think we should explicitly mention about this in a note since some users may not expect this behaviour.

@ahmetmircik can help about details.

**Comment by Serdaro** [comment]
@alparslanavci , I believe IMap.clear() is a map-wide operation, for which we say "A map-wide event is fired as a result of a map-wide operation: for example, IMap#clear or IMap#evictAll." in the Reference Manual. This implies the event "entryRemoved" will not be fired. Nonetheless, I will put a note under the section "Listening for Map Events"
