### ISSUE TITLE
add documentation on disabling index cache 

### ISSUE THREAD

**Issue by gAmUssA** [hazelcast/hazelcast-reference-manual#160]
`MapConfig.setCacheDeserializedValues(CacheDeserializedValues.NEVER)`

**Comment by Serdaro** [comment]
Please see https://github.com/hazelcast/hazelcast/blob/812efa7d6bcb286740f8b73fbaae10e37678d3ef/hazelcast/src/main/resources/hazelcast-full-example.xml#L654 and https://github.com/hazelcast/hazelcast/blob/812efa7d6bcb286740f8b73fbaae10e37678d3ef/hazelcast/src/main/resources/hazelcast-full-example.xml#L647
