### ISSUE TITLE
Semaphore fairness

### ISSUE THREAD

**Issue by ttaomae** [hazelcast/hazelcast-reference-manual#180]
If I understand the [`ISemaphore` Javadoc](https://github.com/hazelcast/hazelcast/blob/v3.6.4/hazelcast/src/main/java/com/hazelcast/core/ISemaphore.java#L29-L42) correctly, it sounds like the `acquire()` method is fair, but `acquire(int)` is not.

The `ISemaphore` section of the reference manual states that the "Hazelcast Semaphore does not support fairness." It also states that "If there is contention, the longest waiting thread will acquire the permit before all other threads." This seems to describe a fair semaphore and is contradictory to the first statement without the context of `acquire(int)`. However, the reference manual does not appear to make any reference to `acquire(int)` so it is not clear from reading just the manual whether semaphores are fair or not.

Could the `ISemaphore` section be updated to make it more clear what fairness guarantees are provided?

**Comment by Serdaro** [comment]
@ttaomae , sorry for the late reply due to the new release tasks. I am going to talk with our developers for the purpose of a more clarified explanation on this.
