### ISSUE TITLE
Extending Hazelcast section missing client details

### ISSUE THREAD

**Issue by ihsandemir** [hazelcast/hazelcast-reference-manual#183]
The following section is missing how the client needs to be extended: http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#extending-hazelcast

It was reported at https://groups.google.com/forum/#!topic/hazelcast/QS1UovGLOhQ

**Comment by Serdaro** [comment]
@ihsandemir , Are you going to provide the content or should I look into the binary client protocol documentation?

**Comment by Serdaro** [comment]
It will already be documented when https://hazelcast.atlassian.net/wiki/spaces/PM/pages/55247287/User-friendly+Client+SPI is realized.
