### ISSUE TITLE
Operation Executor ( HazelcastInstance.ManagedExecutorService ) mentioned in "JMX API per Node" section does not exit anymore

### ISSUE THREAD

**Issue by netudima** [hazelcast/hazelcast-reference-manual#188]
http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#jmx-api-per-node mentions Operation Executor ( HazelcastInstance.ManagedExecutorService ), according to the source code of Hazelcast, in latest versions there is no such executor anymore, so the section is out of date.

**Comment by Serdaro** [comment]
Thank you @netudima , let me dig it.

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/7eab7f8211e52658a4e8d24f50de9b1eb30207ee
