### ISSUE TITLE
Documentation for quorum is not as per Hz 3.7 version. 

### ISSUE THREAD

**Issue by mukul4u2005** [hazelcast/hazelcast-reference-manual#191]
@Override
            public void onChange(QuorumEvent quorumEvent) {
              if (QuorumResult.PRESENT.equals(quorumEvent.getType())) {
                // handle quorum presence
              } else if (QuorumResult.ABSENT.equals(quorumEvent.getType())) {
                // handle quorum absence
              }
            }
        });

**Comment by Serdaro** [comment]
Thank you so much @mukul4u2005
