### ISSUE TITLE
Bug in getting-started guide

### ISSUE THREAD

**Issue by SoothingMist** [hazelcast/hazelcast-reference-manual#202]
The server code at http://docs.hazelcast.org/docs/3.7/manual/html-single/index.html#starting-the-member-and-client is incorrect. It builds but will not run due to not finding certain classes. The server code at https://hazelcast.org/getting-started is correct. It builds and runs just fine.

Had no problem with the client code.

Recommend a bit more detail in how to run the examples. This is not obvious to those not familiar with Java or Maven in sufficient depth. Here is what I did to get things working:

SERVER

Build:
javac -classpath /home/evanhoe/Raeth/hazelcast-3.7.1/lib/hazelcast-3.7.1.jar Server.java

Run:
java -classpath /home/evanhoe/Raeth/hazelcast-3.7.1/lib/hazelcast-3.7.1.jar:. Server

CLIENT

Build:
javac -classpath /home/evanhoe/Raeth/hazelcast-3.7.1/lib/hazelcast-3.7.1.jar:/home/evanhoe/Raeth/hazelcast-3.7.1/lib/hazelcast-client-3.7.1.jar Client.java

Run:  
java -classpath /home/evanhoe/Raeth/hazelcast-3.7.1/lib/hazelcast-3.7.1.jar:/home/evanhoe/Raeth/hazelcast-3.7.1/lib/hazelcast-client-3.7.1.jar:. Client

**Comment by Serdaro** [comment]
Sorry for the late reply @SoothingMist , I will clarify the whole section with the developers.

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/8d842b28706237f513756aac788562ba106b5010.
