### ISSUE TITLE
A cosmetic change in WAN replication section

### ISSUE THREAD

**Issue by Sergeant007** [hazelcast/hazelcast-reference-manual#213]
>ACK_ON_RECEIPT: Events that are received by target cluster that are considered as successful. This option does not guarantee that the received event is actually applied but it is faster.

I think the first sentence should be grammatically fixed. Probably following makes more sense: "Replication batch is considered successful as soon as it received by target cluster"

**Comment by Serdaro** [comment]
Thank you @Sergeant007. @emrahkocaman , WDYT?

**Comment by emrahkocaman** [comment]
@Serdaro I agree, first sentence is grammatically wrong.
I'd like to change @Sergeant007 's suggestion to;
"A batch of replication events is considered successful as soon as it's received by target cluster."
Your choice.

**Comment by Serdaro** [comment]
Thank you, I will change it accordingly.
