### ISSUE TITLE
Improve explanation of `capacity` in Durable Executor service

### ISSUE THREAD

**Issue by gsaslis** [hazelcast/hazelcast-reference-manual#231]
In the `Configuring Durable Executor Service` section, it is not very clear what the `capacity` attribute represents, as it just says: 

`capacity: Capacity of the executor task. 0 means Integer.MAX_VALUE.`

I assume (looking at the `9.1.8 Configuring Executor Service` section) that it is the queue capacity - i.e. the number of tasks the queue can hold - but it would be good to clarify it there too.

**Comment by Serdaro** [comment]
Thanks a lot for pointing out @gsaslis
