### ISSUE TITLE
fix the nearcache eviction config default size paramter

### ISSUE THREAD

**Issue by gurbuzali** [hazelcast/hazelcast-reference-manual#232]
`size: Maximum size of the Near Cache used for max-size-policy. When this is reached the Near Cache is evicted based on the policy defined. Any integer between 0 and Integer.MAX_VALUE. 0 means Integer.MAX_VALUE. Its default value is 0.`

default value for size is `EvictionConfig.DEFAULT_MAX_ENTRY_COUNT` which is `10000`
only positive numbers can be set for the size, 0 is not an option

credit for the issue https://groups.google.com/d/msgid/hazelcast/f9ceb246-c651-4064-9402-1641940b9956%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by Donnerbart** [comment]
I'll pick this up, maybe we have to adjust the XSD etc. as well.
