### ISSUE TITLE
Reliable Topic

### ISSUE THREAD

**Issue by rajavikram** [hazelcast/hazelcast-reference-manual#241]
At the  [link](http://docs.hazelcast.org/docs/3.8/manual/html-single/index.html#reliable-topic) 
`ReliableTopicConfig rtConfig = config.getReliableTopicConfig();` -This is wrong.
Could not find any declaration which takes no arguments.

**Comment by Serdaro** [comment]
Thanks a lot for pointing out @rajavikram
