### ISSUE TITLE
No key access

### ISSUE THREAD

**Issue by gmborisov** [hazelcast/hazelcast-reference-manual#242]
https://hazelcast.org/mastering-hazelcast/#good-to-know-5 Here it says that it`s impossible to access key using SQLPredicate. But in manual http://docs.hazelcast.org/docs/latest/manual/html-single/index.html#distributed-query in section _Querying Entry Keys with Predicates_ it sais it possible to access key using __key attribute

**Comment by Serdaro** [comment]
Thanks a lot for spotting @gmborisov , the information in the manual is correct. I fixed the one in the book, it will be with correct information with its next release.
