### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by bensonhon** [hazelcast/hazelcast-reference-manual#283]
In the doc: http://docs.hazelcast.org/docs/3.8.2/manual/html-single/index.html#replicated-map

Issue #1:
**backup-count**: Defines the number of **asynchronous backups**. For example, if it is set to 1, backup of a partition will be placed on one other member. If it is 2, it will be placed on two other members.
**async-backup-count**: The number of **synchronous backups**. Behavior is the same as that of the backup-count element.

Issue #2:
config.getMapConfig("map").setBackupCount(1); // might lose data if any member crashes
But everywhere else saying setting it to 1 means the data will copy to another member

**Comment by Serdaro** [comment]
Thank you @bensonhon , 
Just to be on the safe side, I couldn't find the listed issues in the link you gave. But I found them at http://docs.hazelcast.org/docs/3.8.2/manual/html-single/index.html#configuring-multimap and http://docs.hazelcast.org/docs/3.8.2/manual/html-single/index.html#listening-for-map-events. I will look into them.

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/3265a438bc76b3b6696f090a925ebabaca5c9498 and https://github.com/hazelcast/hazelcast-reference-manual/commit/6c8caa6c3783be1ca1b91afa15f035194692d9bd. Thanks a lot @bensonhon.
