### ISSUE TITLE
latest: too granular.

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast-reference-manual#290]
For example:

http://docs.hazelcast.org/docs/latest-development/manual/html/Management/Diagnostics/index.html

Then I see one line on the screen. I need to click on 'next' to click to something else that might be relevant..or not... no idea.. can't determine that based on next.

It makes reading the diagnostics documentation almost impossible

**Comment by Serdaro** [comment]
How about making the whole section merged into a single page @pveentjer ?

**Comment by pveentjer** [comment]
I think that would be the best solution in this case.

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/c228831403b42b326747deed7736ee873bbaa3b6

The updated manual is being uploaded to the site.
