### ISSUE TITLE
latest: tree is not constant when clicking next

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast-reference-manual#291]
When starting on this page:

http://docs.hazelcast.org/docs/latest-development/manual/html/Management/Diagnostics/index.html

And I click on next... then the tree next to it changes completely.

before:
![screenshot_2017-07-14_12-26-10](https://user-images.githubusercontent.com/105243/28206753-d297cb2a-688f-11e7-85da-2fdd4ccd5d45.png)
after:
![screenshot_2017-07-14_12-26-29](https://user-images.githubusercontent.com/105243/28206752-d2944630-688f-11e7-9a20-0aa9f45776a9.png)

I have no clue where I am.

**Comment by pveentjer** [comment]
The problem is that the tree scrolled down a lot while clicking on the link. This makes it very confusing to keep track where you are.

**Comment by Serdaro** [comment]
Yes, I had added a script that has being used in the old layout (fix the TOC at the clicking location). But, I guess it does not work well with this new layout. I will try to look at that javascript and improve if I can. If not, I will remove that script.

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/cac2ed64bde82a332da8ec347ab94075c0c240f7.
