### ISSUE TITLE
Missing dispose functionality description in > 3.8

### ISSUE THREAD

**Issue by pawcik** [hazelcast/hazelcast-reference-manual#293]
Hi,

The reference manual for 3.8 do include the changes from 8b72846842b0481e105d42590d6cd00607938647.

I did notice that the reference manual >= 3.8.1 miss the above description. Is it that since 3.8.1 these comments are not relevant anymore?

**Comment by Serdaro** [comment]
I think that is my bad, because I see them also in 3.9-EA reference manual. @tkountis ,  Could you please confirm that those changes are for 3.8 and higher versions, so that I can update 3.8.x docs?

**Comment by Serdaro** [comment]
Updated the 3.8.x manuals and uploaded them to the site.
