### ISSUE TITLE
hazelcast.client.statistics.enabled property is not documented anywhere

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast-reference-manual#294]
During review of the samples, I found hazelcast.client.statistics.enabled property. This property should enable sending client statistics to the member and thus make it visible in Management Center.  

I haven't found any documentation regarding this and related hazelcast.client.statistics.period.seconds property. I would be happy to create a PR with documentation fix, just could somebody help me find a right place in the reference manual? Should it be in the Management Center section? Client section?

**Comment by Serdaro** [comment]
@Holmistr , both properties are mentioned in http://docs.hazelcast.org/docs/latest-development/manual/html/Hazelcast_Clients/Java_Client/Client_System_Properties.html

I will talk with the Clients team to form a relation between the IMDG reference manual and Management Center reference manual.

**Comment by Serdaro** [comment]
As I stated, the property definitions are in the latest-development manual. When the Management Center side is updated with this new development (hopefully with 3.9 GA, as the Integration team says), the relation between two documents will be established.
