### ISSUE TITLE
Typo in lifecycle events sections CLINET_DISCONNECTED

### ISSUE THREAD

**Issue by brianolsen87** [hazelcast/hazelcast-reference-manual#305]
http://docs.hazelcast.org/docs/latest/manual/html-single/index.html#listening-for-lifecycle-events

> CLINET_DISCONNECTED: A Hazelcast Client disconnected from the cluster.

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/ba82085e5f971285eb5553cf2c2e3cb5e80943d2

Thanks a lot @brianolsen87
