### ISSUE TITLE
missing ' ; ' at example in  '8.1.1 Getting a Map and Putting an Entry'' chapter 

### ISSUE THREAD

**Issue by Sudeepa14** [hazelcast/hazelcast-reference-manual#307]
http://docs.hazelcast.org/docs/latest/manual/html-single/index.html#getting-a-map-and-putting-an-entry

See the highlighted line **capitalcities.put( "120", "Stockholm" )**

public class FillMapMember {`
  public static void main( String[] args ) { 
    HazelcastInstance hzInstance = Hazelcast.newHazelcastInstance();
    Map<String, String> capitalcities = hzInstance.getMap( "capitals" ); 
    capitalcities.put( "1", "Tokyo" );
    capitalcities.put( "2", "Paris” );
    capitalcities.put( "3", "Washington" );
    capitalcities.put( "4", "Ankara" );
    capitalcities.put( "5", "Brussels" );
    capitalcities.put( "6", "Amsterdam" );
    capitalcities.put( "7", "New Delhi" );
    capitalcities.put( "8", "London" );
    capitalcities.put( "9", "Berlin" );
    capitalcities.put( "10", "Oslo" );
    capitalcities.put( "11", "Moscow" );
    ...
    ...
    capitalcities.put( "120", "Stockholm" )
  }
}

**Comment by Serdaro** [comment]
Thanks a lot @Sudeepa14

**Comment by Sudeepa14** [comment]
👍
