### ISSUE TITLE
Mention of GroupProperty in the manual

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast-reference-manual#31]
I found a single mention of `GroupProperty` in the manual, which should be removed. That class is part of the internal API. Also the actual text is wrong :)

Map-Persistence.md
> You can set per node maximum capacity with `GroupProperty#MAP_WRITE_BEHIND_QUEUE_CAPACITY`

The correct code would be `GroupProperties#PROP_MAP_WRITE_BEHIND_QUEUE_CAPACITY`, but please replace this with a link to the system properties section or the property name `hazelcast.map.write.behind.queue.capacity`.

**Comment by Serdaro** [comment]
:+1:
