### ISSUE TITLE
Missing example on how to configure the com.hazelcast.core.PartitioningStrategy in XML or API

### ISSUE THREAD

**Issue by noctarius** [hazelcast/hazelcast-reference-manual#313]
By default the partitioning strategy for PartitionAware is activated but the docs are missing an example on how to activate another strategy as well as what strategies are provided by Hazelcast.

subsection: data affinity

**Comment by Serdaro** [comment]
@noctarius , in the config.xsd's, I see that the element <partition-strategy> is commented out. Could you please direct me to a resource on this.

I got this: (https://github.com/hazelcast/hazelcast/blob/d1bae9c134322830de8d4888351f56eb8b5b2de6/hazelcast/src/main/java/com/hazelcast/config/PartitioningStrategyConfig.java). But not enough code comments there.

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/13c3fe0ff8009754d5a5181f58e1ba67df73869f.
