### ISSUE TITLE
Missing example how to configure member attributes in XML

### ISSUE THREAD

**Issue by noctarius** [hazelcast/hazelcast-reference-manual#314]
The docs are missing an example on how member attributes can be configured in XML or using the Config API before the actual node starts.

Something like:
```
<member-attributes>
  <attribute name="hazelcast.partition.group.zone">${dc.name}</attribute>
</member-attributes>
```

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/e4026a99c131f3e4a70340054f8d22d2b3b519f4
