### ISSUE TITLE
Eager loading unclear

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast-reference-manual#317]
I'm a HZ engineer and I have no clue what it means or what the purpose is.
```
initial-mode: Sets the initial load mode. LAZY is the default load mode, where load is asynchronous. EAGER means load is blocked till all partitions are loaded.
```

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/75a47a943e6763c848c4c92396d1ea966e4ef856
