### ISSUE TITLE
Confusing x-link between IMap and JCache documentation

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast-reference-manual#321]
The first first link in the IMap Eviction chapter points to [JCache specific page](http://docs.hazelcast.org/docs/latest-development/manual/html/Hazelcast_JCache/Hazelcast_JCache_Extension-ICache/JCache_Eviction.html):
![image](https://user-images.githubusercontent.com/158619/29870652-5ba9449a-8d91-11e7-9205-f8d5e4825964.png)

It's quite confusing as the page uses very JCache specific language and I believe it adds to the common confusion caused by duality IMap - JCache.

I think there is no need to hurry with explaining these details to users. I reckon most of our users simply want to know how to configure Eviction. Explanation of the probabilistic algo should not be on top of the page.

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/44769854152d6562f772ec0f7a14748defc5cc29
