### ISSUE TITLE
There's no more concrete class HazelcastCacheManager

### ISSUE THREAD

**Issue by tzvatot** [hazelcast/hazelcast-reference-manual#332]
I'm using hazeclast 3.6.2.
HazelcastCacheManager now an abstract class, and the documentation is wrong: I cannot create an instance:
` new HazelcastCacheManager();`

**Comment by vbekiaris** [comment]
hi @tzvatot , thanks for reporting this issue. The only occurence of `new HazelcastCacheManager` I see is in section [Annotation-Based Spring Cache Configuration](http://docs.hazelcast.org/docs/3.6.2/manual/html-single/index.html#adding-caching-to-spring). This section is about configuring Spring and refers to class `com.hazelcast.spring.cache.HazelcastCacheManager` from `hazelcast-spring` module which is a proper concrete class. I guess there was some confusion with interface `com.hazelcast.cache.HazelcastCacheManager`. Maybe we should show the fully-qualified class name in the code sample, wdyt @Serdaro ?

**Comment by Serdaro** [comment]
Thanks a lot for the notes, recommendation and help @vbekiaris
