### ISSUE TITLE
Information about the Lock

### ISSUE THREAD

**Issue by moonglum** [hazelcast/hazelcast-reference-manual#337]
The reference manual states [here](http://docs.hazelcast.org/docs/3.8.6/manual/html-single/index.html#lock):

> ILock is the distributed implementation of java.util.concurrent.locks.Lock, meaning that if you lock using an ILock, the critical section that it guards is guaranteed to be executed by only one thread in the entire cluster.

This is only guaranteed in the case that there is no network failure. In my opinion, this should be stated right from the beginning because it might be misleading otherwise. What do you think?

**Comment by Serdaro** [comment]
Absolutely @moonglum , I will add that phrase to that sentence. Thanks a lot.

**Comment by moonglum** [comment]
Thank you, @Serdaro 🙇
