### ISSUE TITLE
Add info about blacklisted package names for client code deployments

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast-reference-manual#338]
There is a blacklist used for deploying client code. Make sure the blacklist rules/expressions are described in the manual.

Details are in hazelcast/hazelcast#11558

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/eab4a31678322075156f22fb341cc856923c7eea

**Comment by Serdaro** [comment]
Also this commit: https://github.com/hazelcast/hazelcast-reference-manual/commit/cea136c5132d359c5a2fc7b6662ef984114789c3
