### ISSUE TITLE
Document property hazelcast.shutdownhook.policy

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast-reference-manual#345]
Document the `hazelcast.shutdownhook.policy` property in reference manual.

The `hazelcast.shutdownhook.policy` Hazelcast property configures shudown policy. It allows to enable `GRACEFUL` shutdown when `SIGTERM` comes. The default value is `TERMINATE`.

Links:
* https://github.com/hazelcast/hazelcast/blob/v3.9-EA/hazelcast/src/main/java/com/hazelcast/spi/properties/GroupProperty.java#L310-L324
* https://github.com/hazelcast/hazelcast/blob/v3.9-EA/hazelcast/src/main/java/com/hazelcast/instance/Node.java#L610-L643

**Comment by Serdaro** [comment]
Thanks a lot @kwart
