### ISSUE TITLE
Document management center usage for rolling upgrade and the limitations

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast-reference-manual#346]
After rolling upgrade is finished, you need to manually change the cluster version, one of the options to do that is management center. There are some information missing regarding this:

- if you want to do it via Management center, you first have to upgrade mancenter to the newer version (the one that you're upgrading your members to)
- related: https://github.com/hazelcast/mancenter-reference-manual/issues/22
- I would expect a link from http://docs.hazelcast.org/docs/latest-development/manual/html/Rolling_Member_Upgrades.html , where the is the Management center option mentioned to the section in Management Center reference manual mentioned above.

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/f3fa3b35544bd62f0806bc158d0dc0dc8599c7d5
