### ISSUE TITLE
3.9 Reference manual - 2 Document Revision History - wrong anchors

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast-reference-manual#351]
Some links in the "Document Revision History" chapter has non-existing anchors:

* #ldap-authentication
* #active-directory-authentication
* #jaas-authentication
* #password-encryption
* #ssl
* #validating-secrets-using-strength-policy
* #integrating-with-spring
* #dynamically-adding-configuration-on-a-cluster
* #;
* #user-code-deployment

**Comment by Serdaro** [comment]
Fixed unresolved cross-references in 3.9 branch, and uploaded the updated manual to the site. 
Note: Removed the Management Center subsection links and added a note there, since the whole section content was moved to Management Center's own manual.
Thanks.
