### ISSUE TITLE
Chapter 4: Hazelcast overview review

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast-reference-manual#352]
Some thoughts, ideas, suggestions regarding chapter 4 in the reference manual (http://docs.hazelcast.org/docs/3.9/manual/html-single/index.html#hazelcast-overview)

- Initial paragraphs, sentence: "Hazelcast is highly scalable and available (100% operational, never failing)" - remove the "(100% operational, never failing)", this is just redundant and a target to our head if anything goes wrong.
- Initial paragraphs, sentence: "Hazelcast also speaks memcache protocol." should be changed to "Hazelcast also speaks Memcached protocol."
- (optional - just for consideration) Section http://docs.hazelcast.org/docs/3.9/manual/html-single/index.html#hazelcast-topology , sentence "If you have an application whose main focal point is asynchronous or high performance computing and lots of task executions, then Embedded deployment is useful." - the word "useful" seems a bit weird to me here, embedded mode is useful even in other scenarios. Maybe something like "way to go", "prefered"?
- Section http://docs.hazelcast.org/docs/3.9/manual/html-single/index.html#why-hazelcast , sentence "... problems--when data changes ..." - perhaps a dash is a better option.

**Comment by Serdaro** [comment]
Can be closed because of https://github.com/hazelcast/hazelcast-reference-manual/pull/390
