### ISSUE TITLE
3.9 Reference manual - 5 Understanding Configuration - review 

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast-reference-manual#355]
Issues found during 3.9 Reference manual review in chapter 5 - Understanding configuration:

## Incomplete XML configuration snippet ###

First code snippet in section http://docs.hazelcast.org/docs/3.9/manual/html-single/index.html#configuring-declaratively is incomplete and thus not working. It should be, e.g.:
```xml
<group>
        <name>dev</name>
        <password>dev-pass</password>
    </group>
    <management-center enabled="false">http://localhost:8080/mancenter</management-center>
    <network>
        <port auto-increment="true" port-count="100">5701</port>
        <outbound-ports>
            <!--
            Allowed port range when connecting to other members.
            0 or * means the port provided by the system.
            -->
            <ports>0</ports>
        </outbound-ports>
        <join>
            <multicast enabled="true">
                <multicast-group>224.2.2.3</multicast-group>
                <multicast-port>54327</multicast-port>
            </multicast>
            <tcp-ip enabled="false">
                <interface>127.0.0.1</interface>
                <member-list>
                    <member>127.0.0.1</member>
                </member-list>
            </tcp-ip>
        </join>
    </network>

    <map name="default">
        <!--
			Maximum number of seconds for each entry to stay in the map. Entries that are
			older than <time-to-live-seconds> and not updated for <time-to-live-seconds>
			will get automatically evicted from the map.
			Any integer between 0 and Integer.MAX_VALUE. 0 means infinite. Default is 0.
		-->
        <time-to-live-seconds>0</time-to-live-seconds>
    </map>
```

## Filling placeholder example.

After the code snippet that shows usage of placeholders in declarative configuration: 
```xml
<hazelcast>
  <import resource="${environment}-group-config.xml"/>
  <import resource="${environment}-network-config.xml"/>
</hazelcast>
```
I suggest adding a link to http://docs.hazelcast.org/docs/3.9/manual/html-single/index.html#using-variables to show an example how to pass the value to the variable.

## Typo in code snippet from dynamic configuration
In the Danymically Adding Data Structure Confiugration on a Cluster section (http://docs.hazelcast.org/docs/3.9/manual/html-single/index.html#dynamically-adding-data-structure-configuration-on-a-cluster), there is a code snippet. First line of the code snippet contains ":" at the end of the line instead of ";".

## Typo in Checking Coniguration section
There is a command "- Dhazelcast.config=<path to the hazelcast.xml>." There should be no space between "-" and "Dhazelcast...".

## Typo in code snippet in Using Variables section
In the last code snippet, the line `builder.setProperties(properties)` is missing semicolon (;) at the end of the line.

**Comment by Serdaro** [comment]
Can be closed because of https://github.com/hazelcast/hazelcast-reference-manual/pull/394
