### ISSUE TITLE
3.9 Reference manual - don't use group password in the samples

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast-reference-manual#358]
This issue is related to hazelcast/hazelcast#11667.

There is an ongoing effort related to removing group password from Hazelcast configuration. The password is not checked anymore during member joins. This should be also reflected in the documentation.

**Suggestion for improvement:**
* add a single section explaining how to set the group password for backward compatibility (joining to cluster where are members with version `< 3.8.2`)
* remove the group password configuration from all the other samples across the manual

CC @tkountis : You are the one with deepest knowledge of the current implementation. Could you share your view on this issue? (objections, thoughts, ideas)

**Comment by Serdaro** [comment]
@kwart , @tkountis , There is a note at the very bottom of the [Creating Cluster Groups](http://docs.hazelcast.org/docs/latest-development/manual/html/Setting_Up_Clusters/Creating_Cluster_Groups.html) section:

```
NOTE: Starting with Hazelcast 3.8.2, members with the same group name but with different group passwords (that do not use authentication) forms a cluster. Before this release, group passwords needed to be the same too.
```

I guess this note is irrelevant now?

**Comment by kwart** [comment]
I think the Note should stay - maybe with some clean-up.
The message is important - We used to check the password, but we don't anymore!

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/pull/431
