### ISSUE TITLE
Standardize out-of-the-box phrase

### ISSUE THREAD

**Issue by Serdaro** [hazelcast/hazelcast-reference-manual#386]
There should be no "out of the box".

**Comment by Donnerbart** [comment]
Hazelcast OS: https://github.com/hazelcast/hazelcast/pull/11727
Hazelcast EE: https://github.com/hazelcast/hazelcast-enterprise/pull/1787

**Comment by Serdaro** [comment]
Closed via https://github.com/hazelcast/hazelcast-reference-manual/pull/399

**Comment by Donnerbart** [comment]
The OS and EE PRs are not merged yet :)
