### ISSUE TITLE
There is no documentation for JMX

### ISSUE THREAD

**Issue by muratayan** [hazelcast/hazelcast-reference-manual#40]
Hello,

In the Hazelcast section, there is no documentation for how to use JMX from custom clients. Also there must be a section that explains how to enable JMX agent via configuration. i.e.:

```java
Config config = new Config();
config.setProperty(GroupProperties.PROP_ENABLE_JMX, "true");
```

Also, people can't know how we name the JMX Beans. I'd be happy to help. Because this is not enough: http://docs.hazelcast.org/docs/3.5/manual/html-single/hazelcast-documentation.html#monitoring-with-jmx

**Comment by Serdaro** [comment]
Let's sit down together tomorrow and complete it.

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/401d123e48c75a25b505a89b8c2a8823468bc4e1
