### ISSUE TITLE
3.9 Reference manual - 11. Distributed Query - review

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast-reference-manual#401]
Issues found in chapter 11 "Distributed Query" during review:

## Don't link GitHub classes, but their JavaDoc
Some section in the chapter 11 contains link to a class on 
 GitHub. The JavaDoc should be rather linked than the source code.

* `Predicates` in "Predicates Class Operators" section (the JavaDoc is not in a good shape now. See https://github.com/hazelcast/hazelcast/issues/11734)
* `PagingPredicate` in "Filtering with Paging Predicates" section

**Suggested improvement**
Link the classes in JavaDoc documentation section instead of GitHub sources.

## Remove final note from Paging Predicates section
The "RELATED INFORMATION" note in "Paging Predicates" section, is not related to this section. It's already part of "Predicates Class Operators" section too. It should be removed from the "Paging Predicates".

**Suggested improvement**
Remove the note about `Predicates` class from "Paging Predicates" section

## MarkDown leftover in "Configuring IMap Indexes" section
The final note in section "Configuring IMap Indexes" contains text:
```
...  if you configure the data structure to use High-Density Memory Store **and** indexes ...
```
The two stars (`**`) are a leftover from documentation processing from MarkDown.

**Suggested improvement**
Fix the Markdown formatting so the bold font-weight is used instead of the stars.

## Don't include Hazelcast source code in reference manual
The chapter 11 contains several places with source code of Hazelcast interfaces and classes. It's hard to maintain (keep-up to date) and hard to read (text not wrapped according to screen settings, comment lines starting with star ...).
We provide JavaDoc as a part documentation, so if there is a need to provide details about the interfaces/classes, we should link it (e.g. http://docs.hazelcast.org/docs/3.9/javadoc/com/hazelcast/scheduledexecutor/IScheduledExecutorService.html) instead of copy-pasting the source code.

The problem locations:
- classes `ValueExtractor` and `ValueCollector` in "Implementing a ValueExtractor" section
- class `ValueReader` in "ValueExtractor with Portable Serialization" section
- `Aggregator` class in "Aggregator API" section
- snippet from `IMap` in "Fast-Aggregations and Map Interfaces" section
- `Projection` class in "Projections API" section
- snippet from `IMap` in "Projections and Map Interfaces" section

**Suggested improvement**
Remove the classes source code and if necessary use just links to JavaDoc.

## Update the introduction of MapReduce section - add deprecation warning
Update introduction in section "11.4 MapReduce" - the deprecation of MapReduce API has to be mentioned just on the beginning. It's not sufficient to add the information as a last subsection. This is the most important information.

E.g. the JavaDoc of `JobTracker` says
> MapReduce is deprecated and will be removed in 4.0.
> For map aggregations, you can use `com.hazelcast.aggregation.Aggregator` on `IMap`.
> For general data processing, it is superseded by [Hazelcast Jet](https://jet.hazelcast.org).

**Suggested improvement**
Start the section with an emphasized message about API deprecation. Provide a link to the last subsection of MapReduce section which constains more details.

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/pull/427
