### ISSUE TITLE
hazelcast-client-full referenced in wrong context

### ISSUE THREAD

**Issue by vbekiaris** [hazelcast/hazelcast-reference-manual#418]
In http://docs.hazelcast.org/docs/3.9/manual/html-single/index.html#setting-the-license-key , under "Client Declarative Configuration" the following instructions are provided:

> In that case, you also need to have a Hazelcast Enterprise license and you should include this license in the file hazelcast-client-full.xml which is located under the directory src/main/resources of your hazelcast-client package. Set the license key in the hazelcast-client-full.xml as shown below.

The instructions for setting the license key should not refer to `hazelcast-client-full.xml`; instead it should be clear that this file is just a full client config example (as `hazelcast-full-example.xml` is for member side).

**Comment by Serdaro** [comment]
Can be deemed fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/cc5e20ec82f153bda7b55f95dc96b6926fa135fe#diff-1e81861fa6d79fc585d06e16596190b5 which was a related commit.
