### ISSUE TITLE
3.9 Reference manual - 13. Hazelcast JCache - review

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast-reference-manual#425]
Issues found in chapter 13 "Hazelcast JCache" during review:

## Invalid section: JCache - Hazelcast Instance Integration
This section is outdated and/or wrong. The `HazelcastInstance` doesn't have `getCache(String)` method. It only have `ICacheManager getCacheManager()` method. The `ICacheManager` interface has `getCache(String)` method, but it [handles prefix in a different way](http://docs.hazelcast.org/docs/3.9/javadoc/com/hazelcast/core/ICacheManager.html#getCache-java.lang.String-) (doesn't use /hz/ prefix).

http://docs.hazelcast.org/docs/latest/manual/html-single/index.html#jcache-hazelcast-instance-integration

**Suggested improvement**
Rewrite the "JCache - Hazelcast Instance Integration" section to reflect current API.

## Add details to ICache methods
The "ICache Convenience Methods" section describes additional methods. Their description should be improved
> * size(): Returns the estimated size of the distributed cache.
> * destroy(): Destroys the cache and removes the data from memory. This is different from the method javax.cache.Cache::close.

**Suggested improvement**
For `size()` method explain what does it mean the estimated size. For the `destroy()` method explain how it's different from the `Cache.close()`

## ICache.getLocalCacheStatistics() on clients
The "ICache Convenience Methods" section says the `ICache.getLocalCacheStatistics()` throws an `UnsupportedOperationException` on clients. This seems to be an outdated information as we have a [client code sample](https://github.com/hazelcast/hazelcast-code-samples/blob/v3.9/jcache/src/main/java/com/hazelcast/examples/nearcache/ClientNearCacheUsageSupport.java#L203) calling this method:

**Sugested improvement**
Update the `getLocalCacheStatistics` information in the "ICache Convenience Methods" section.

## Incomplete list in ICache Convenience Methods
The section "ICache Convenience Methods" list 3 methods of ICache, but there are more of them (e.g. `isDestroyed()`, `iterator(int)`, methods to control partitionlost listeners). We don't need to list them one-by-one, but at least some note "there are more of them" should be provided with a link to JavaDoc of ICache.

**Suggested improvement**
Cover the rest of the methods from `ICache` interface, e.g. by providing a link to `ICache` javadoc in the "ICache Convenience Methods" section.

## Update the JCache TCK related section
The section "Testing for JCache Specification Compliance" is outdated:
* the GitHub tag should be referenced to point to the correct TCK version
* there is no `tck-parent/pom.xml` we should talk about `pom.xml` only;
* the XML snippet is not correct and should be reviewed. At least the `jsr107.api.version` property seems to be wrong and the `jcache.version` should be used instead
* the TCK guide links should be provided or mentioned (They are located in the TCK repository README.md file).

**Suggested improvements**
* update steps to use the TCK
* fix the XML snippet and the `pom.xml` location
* mention the TCK guide(s)

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/pull/436/
