### ISSUE TITLE
Changes tracking and Migrations between Hazelcast versions in the Reference manual

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast-reference-manual#435]
Opening discussion about versions tracking and migrations.

I would like to see following enhancements  in the Reference manual:
* Don't describe changes between Hazelcast versions in the Reference manual. Just describe features of the specific Hazelcast version for which is the manual released.
* move the upgrade/migration related documentation to a separate documents - one for each minor version.

The reference manual often says something like "Starting with version 3.X users can YYYY". IMO the reference manual for a specific version should just say - we have this feature (without specifying where it did into Hazelcast). The changes between versions should be tracked only in the Release notes and/or a Upgrade/Migration documentation.

**Suggested improvement**
* describe the feature without specifying a version from which the information is valid (i.e. it's valid in the current version for which we release the reference manual)
* move the Upgrade related documentation to a new Migration documents (one for each minor version) - describe there a migration path from the previous version and how to handle the important changes (API changes, deprecations, switching a feature to a new implementation).

**Comment by Serdaro** [comment]
@jerrinot , Do you have any comments for the above? Is having a separate migration document good idea, or can we use the current release notes documents for this?

**Comment by jerrinot** [comment]
do we have enough migration-related content which would deserve its own document? isn't a section in the ref manual enough? there where I would expect it to be.

**Comment by Serdaro** [comment]
+1. We have "Upgrading.." sections in the reference manual, Release Notes documents and also a changelog.txt delivered with the package for each release. I am in favor of continuing this practice. 

About not stating the "Starting with..." phrases, I think you are right.

 @kwart , any additional comments on this discussion?

**Comment by kwart** [comment]
The extra migration document is not a hard requirement, but IMO it would make things more clear.  Moving the Upgrading section to appendix could also help.

What I don't like on the current Reference manual is the "Upgrading" section talks for instance about "Upgrading from **3.6.x** to **3.7.x** when using JCache". Where is the value of such information for 3.9.3 users?

I can imagine the Upgrading section talks about upgrading from 3.(y-1) to 3.y and possible changes in the z-stream (patches). I would like to avoid keeping there points unrelated to the version of the Reference manual..

**Comment by Serdaro** [comment]
Ok, let me work on this during the 3.10 works. Thanks a lot for the comments all.
