### ISSUE TITLE
'Configuring Client Connection Strategy' is incorrect in reference manual

### ISSUE THREAD

**Issue by neilmendum** [hazelcast/hazelcast-reference-manual#444]
I was investigating the same issue as [9692](https://github.com/hazelcast/hazelcast/issues/9692) so was happy this was added in 3.9 only a few weeks ago

[In the v3.9 docs](http://docs.hazelcast.org/docs/3.9/manual/html-single/index.html#configuring-client-connection-strategy)

> ClientConfig clientConfig = new ClientConfig();
clientConfig.getClientConfigurationStrategy()
            .setAsyncStart(true)
            .setReconnnectMode(ReconnectMode.ASYNC);

However looking at the [ClientConfig source](https://github.com/hazelcast/hazelcast/blob/master/hazelcast-client/src/main/java/com/hazelcast/client/config/ClientConfig.java) there is no getter for `ClientConfigurationStrategy`
So I believe the docs should be: 
> clientConfig.getConnectionStrategyConfig()
.setAsyncStart(true)
.setReconnectMode(ClientConnectionStrategyConfig.ReconnectMode.ASYNC);

**Comment by Serdaro** [comment]
Thanks a lot @neilmendum 👍
