### ISSUE TITLE
3.9 Reference Manual 17 Hazelcast Java Client thread count display problem

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast-reference-manual#450]
it is rendered as `core count 10*` however, it should be `core count * 10`. 
Please note that in Idea MD renderer shows it properly. Therefore, I open this issue.

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/858c6b0680cfcf91b0568b01c2ace889a143f3cb. Thank you @lazerion
