### ISSUE TITLE
3.9 Reference Manual 17 Hazelcast Java Client Swing mention can be updated

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast-reference-manual#451]
`... Swing/Web applications ...`
Swing is kind of obsolete, IMO it should be replaced.

**Comment by Serdaro** [comment]
@lazerion , removed maybe?

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/8f478c8b1902005de73088fa1a13adc875351c01 .
