### ISSUE TITLE
Extend documentation for the metrics of Map Stats

### ISSUE THREAD

**Issue by ncherkas** [hazelcast/hazelcast-reference-manual#470]
[Here](http://docs.hazelcast.org/docs/latest-development/manual/html/Management/Getting_Member_Statistics/Map_Statistics.html#page_Map+Statistics) there is a code sample of `LocalMapStats` object where documentation of some properties is quite limited. It would be good to extend it. Here is a description of properties `Hits` and `Events`:

_Hits is the metric which is showing the number of times when an operation on `IMap` was routed to the given member. With Clustered REST API it's showing the total sum of hits among cluster members. As for the events, this is about operations that were invoked on `IMap` entries. List of event types includes the following: insertion, update, removal, eviction, clear all, merge, expiration and invalidation._

Please let me know if you need a help with getting more info about other properties.

**Comment by Serdaro** [comment]
Thank you @ncherkas , will do.
