### ISSUE TITLE
Mancenter WAN Tab Section is missing Clear Queues” functionality

### ISSUE THREAD

**Issue by sertugkaya** [hazelcast/hazelcast-reference-manual#494]
we neither have the “Clear Queues” functionality explained nor the button for that shown in the mancenter WAN tab in screenshots here.
http://docs.hazelcast.org/docs/management-center/3.9.2/manual/html/Monitoring_WAN_Replication.html

**Comment by Serdaro** [comment]
Moving to https://github.com/hazelcast/mancenter-reference-manual
