### ISSUE TITLE
Defining WAN replication section image not displayed and dangling `+`

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast-reference-manual#499]
Hi Team
http://docs.hazelcast.org/docs/latest-development/manual/html/WAN_Replication/Defining_WAN_Replication.html

In the image below, image is not displayed and there seems to be dangling `+` sign.
<img width="1235" alt="screen shot 2018-03-21 at 11 26 32" src="https://user-images.githubusercontent.com/6961620/37699995-feab7fec-2cfa-11e8-86a6-66082abe3488.png">

Also similar in http://docs.hazelcast.org/docs/latest-development/manual/html/Setting_Up_Clusters/Other_Network_Configurations.html#page_aws+element
<img width="1197" alt="screen shot 2018-03-21 at 11 29 58" src="https://user-images.githubusercontent.com/6961620/37700115-5abbc71a-2cfb-11e8-9577-098c203d7182.png">

**Comment by Serdaro** [comment]
Thanks @lazerion
