### ISSUE TITLE
Extend Continuous Query Cache documentation

### ISSUE THREAD

**Issue by yozank** [hazelcast/hazelcast-reference-manual#505]
CQC is one of the most widely used features of Hazelcast but the related documentation is missing some details. For example, it is not clear how the relationship is between `batchSize`, `bufferSize`, `delaySeconds` and `coalesce`. One needs to dive into the source code to learn about them. 
The publisher and subscriber logic could be described in more detail. 

The following is some work I did for detailing the `CQC publishing logic`. This can be improved to a better language and explanation.

**Publisher Logic** 

If the `delaySeconds` <= 0 (default 0), then `batchSize` loses its function. 
Each time there is an event, all the entries in the buffer are pushed to the subscriber.

Otherwise, if `delaySeconds` > 0 then the following logic applies:

if `coalesce` is set, the buffer is checked if there is an event with the same key. If so, it is overridden by the current event. 

Then; 
a)  The current size of the buffer is checked. 
If the current size of the buffer >= `batchSize`, then `batchSize-counted` events are pushed to the subscriber. 
Otherwise, no events are sent.
b) Then, after finishing with checking `batchSize`, `delaySeconds` is checked. 
The buffer is scanned from oldest to youngest, all the entries that are older than `delaySeconds` are pushed to the subscriber.

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/3142cd6b576af6e2e500def6ecede9bd042bb0e3
