### ISSUE TITLE
Add more details for using Hazelcast with Spring

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast-reference-manual#511]
This issue is based on hazelcast/hazelcast#11872 and related discussion in hazelcast/hazelcast-code-samples#219

**Issue description**

Hazelcast configuration and integration with Spring can differ across Spring versions. We should reflect it in the reference manual. Currently the compatibility topic is covered by "Supported Versions" section, which says:
> Spring 2.5+

**Suggested improvement**
* Provide a warning that different Spring versions may require different handling;
* Describe for which Spring version are the snippets in the manual valid.

**Comment by mesutcelik** [comment]
What about adding latest tested version to the manual as well?
Currently it is [4.3.0.RELEASE](https://github.com/hazelcast/hazelcast/blob/master/hazelcast-spring/pom.xml#L36
)

We can always add problematic configuration as seen in https://github.com/hazelcast/hazelcast-code-samples/pull/219 to Troubleshooting section. For the https://github.com/hazelcast/hazelcast/issues/11872, It can be upgrading to `4.2.9.RELEASE` or a later version as @emre-aydin suggested [here](https://github.com/hazelcast/hazelcast-code-samples/pull/219#issue-174292543)
