### ISSUE TITLE
Update reference manual and javadoc for latest updates to split brain merging

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast-reference-manual#515]
We need to add additional information to the ref manual and the javadoc, caused by the latest changes to the split merge functionalities.

- document behaviour and allowed return values from merge policy. See comment: https://github.com/hazelcast/hazelcast/pull/12827#pullrequestreview-111970467
- document difference in behaviour between key-based and keyless data structures (ISet, IList, IQueue, Ringbuffer). See: https://hazelcast.slack.com/archives/C846ED119/p1523541341000066 and https://hazelcast.slack.com/archives/G6EDCRY49/p1523623051000582

**Comment by Serdaro** [comment]
@mmedenjak , please check https://github.com/hazelcast/hazelcast-reference-manual/pull/517/

I did copyedit the content and applied the updates to branches 3.10 and maintenance-3.x too.

**Comment by mmedenjak** [comment]
Looks good, thanks @Donnerbart !
