### ISSUE TITLE
System properties format issue

### ISSUE THREAD

**Issue by gokhanoner** [hazelcast/hazelcast-reference-manual#516]
For some properties, the table seems shifted: Please see http://docs.hazelcast.org/docs/latest-development/manual/html/System_Properties/System_Properties_-_Member.html

Please check `hazelcast.clientengine.query.thread.count` property

**Comment by Serdaro** [comment]
Thank you @gokhanoner , known issue. It has been fixed on the current master production manual and upcoming AsciiDoc outputs.
