### ISSUE TITLE
WAN sync for all maps is not documented

### ISSUE THREAD

**Issue by sertugkaya** [hazelcast/hazelcast-reference-manual#529]
The endpoint `https://127.0.0.1:5701/hazelcast/rest/mancenter/wan/sync/allmaps` is not mentioned in the docs.

**Comment by Serdaro** [comment]
Also https://github.com/hazelcast/mancenter-reference-manual/commit/a326cff5198fe5f9f478af1236bcc3e20f2a1c2f for Management Center Reference 
Manual.
