### ISSUE TITLE
New hazelcast.xml element not documented in ref manual.

### ISSUE THREAD

**Issue by dbrimley** [hazelcast/hazelcast-reference-manual#544]
``<security>
        <client-block-unmapped-actions>true</client-block-unmapped-actions>
 </security>``

There seems to be this in the XSD schema...
"Block or allow actions, submitted as tasks in an Executor from clients and have no permission mappings."

**Comment by Serdaro** [comment]
Fixed with  https://github.com/hazelcast/hazelcast/commit/a25f51db5fa596162add9cab6a1a12a1fd142146#diff-8787fd9af4d211a60ce1c9edc453dfd9
