### ISSUE TITLE
Hazelcast Cloud Discovery Configurations

### ISSUE THREAD

**Issue by sancar** [hazelcast/hazelcast-reference-manual#545]
Related design document https://hazelcast.atlassian.net/wiki/spaces/PM/pages/650805252/Java+Client+Hazelcast+Cloud+Discovery+Design+Document

The implementation will be out with 3.10.3 and 3.11
But we want to document this feature when hazelcast.cloud is out. So adding this to referance manual will wait for the hazelcast.cloud release. 

Note that the configurations are different in 3.10.3 and 3.11. 

We need to add an extra paragraph regarding security. See
https://hazelcast.atlassian.net/wiki/spaces/PM/pages/650805252/Java+Client+Hazelcast+Cloud+Discovery+Design+Document#JavaClient:HazelcastCloudDiscoveryDesignDocument-Security

**Comment by sancar** [comment]
It it decided that we want to document this right now in 3.11.

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/eab061ad4436a05cbcc90634a31044b7c2cdfbb4
