### ISSUE TITLE
Incomplete text in "Indexing Custom Attributes"

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast-reference-manual#552]
This chapter looks like a nonsense to me: http://docs.hazelcast.org/docs/3.10.2/manual/html-single/index.html#indexing-custom-attributes
It should be about `ValueExtractor.

**Comment by Serdaro** [comment]
@viliam-durina , the parent section of Indexing Custom Attributes (Section 11.3) actually talks about custom attribute extraction, for which we have currently only one way to do (implementing com.hazelcast.query.extractor.ValueExtractor). And the section you mentioned talks about how to create indexes using custom attributes. Could you please elaborate more on the content enhancement? (even a text suggestion would work).

**Comment by viliam-durina** [comment]
Ok, makes sense now. 

However, I got referred to the chapter from [here](http://docs.hazelcast.org/docs/3.10.2/manual/html-single/index.html#indexing-attributes-with-valueextractor). I was looking for a way how to create an index from two attributes. It referred me to the chapter which looked like nonsense to me because I had no prior knowledge of `ValueExtractor`. The `ValueExtractor` is the hard thing to do when you need such an index. Once you know what `ValueExtractor` is, defining an index is intuitive. It might be better to refer "11.3. Custom Attributes" chapter.

Also the `currency[EUR]` doesn't make much sense. `amount[EUR]` would make more sense.

**Comment by Serdaro** [comment]
@viliam-durina , changed the cross-reference, thank you for the notice. 

About `currency[EUR]`: The sections before http://docs.hazelcast.org/docs/3.10.2/manual/html-single/index.html#indexing-custom-attributes talk about the `currency` as the custom attribute (Sections 11.3.2, 11.3.3 and 11.3.4). Isn't it expected to include it in Section 11.3.5 while giving indexing examples?

**Comment by viliam-durina** [comment]
@Serdaro
True, but they use `currency[incoming]`. This makes sense. `currency[EUR]` doesn't. What do you think the `currency` attribute would return for an argument `EUR`? That doesn't make sense. `currency[incoming]` would return the currency, that is incoming. I imagine that there is also outgoing currency or so.
