### ISSUE TITLE
Describe possibility of using "this" keyword as an attribute name for indexes and predicates

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast-reference-manual#562]
**Issue description**
I don't see a description of using `"this"` as attribute name in reference manual.
It's a keyword, which can be used when user is adding an index or creating a predicate (https://github.com/hazelcast/hazelcast/blob/v3.10.4/hazelcast/src/test/java/com/hazelcast/map/PagingPredicateTest.java#L176-L177).

**Suggested improvement**
Describe the `"this"` keyword usage as an attribute name. The correct location could be in chapter 11. Distributed Query - http://docs.hazelcast.org/docs/latest/manual/html-single/index.html#indexing-queries

**Comment by Serdaro** [comment]
Fixed with #578
