### ISSUE TITLE
Missing: behavior when multiple configurations match

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast-reference-manual#565]
I've read this section: https://github.com/hazelcast/hazelcast-reference-manual/blob/master/src/docs/asciidoc/understanding_configuration.adoc#using-wildcards

One question immediately popped in my mind: what will happen if multiple configurations match? Looking at `MatchingPointConfigPatternMatcher` it also seems that at most one wildcard can be used.

**Comment by Serdaro** [comment]
@viliam-durina , Could you please provide an example for multiple configurations for such a match?

**Comment by viliam-durina** [comment]
My point was that if I have map-configs for both `a.*` and `a.b.*`, which one will be used for map named `a.b.c` because both configs match. Will it be the longest one, or the first one in defining-order, or unspecified one, or something else?

**Comment by Serdaro** [comment]
Hm, thank you. Let me ask to the guys.

**Comment by Serdaro** [comment]
@viliam-durina , Could you please check https://github.com/hazelcast/hazelcast-reference-manual/commit/bc5e3a6da22a22b93d160fcdee3bbf7d5804c247 to see whether it addresses your question?
