### ISSUE TITLE
Client heartbeat parameters correlation need explanation

### ISSUE THREAD

**Issue by sancar** [hazelcast/hazelcast-reference-manual#572]
We need to explicitly say that interval needs to be smaller than timeout under the following heading.
http://docs.hazelcast.org/docs/3.10.4/manual/html-single/index.html#java-client-failure-detectors

And also "hazelcast.client.max.no.heartbeat.seconds" parameter from member side needs to be larger than the `interval`

**Comment by Serdaro** [comment]
@sancar , I have added the note mentioned in the above commit. Please feel free to elaborate more if needed.

**Comment by sancar** [comment]
Thanks @Serdaro . Looks good to me.
