### ISSUE TITLE
Document Scheduler - Spring integration

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast-reference-manual#579]
https://github.com/hazelcast/hazelcast/pull/13550 is adding a support for Spring scheduler integration. It should be documented in the RefMan.

**Comment by Serdaro** [comment]
Added the content with https://github.com/hazelcast/hazelcast-reference-manual/commit/87f8ee462815e06b086d32ad3d88c6205588ed0d and https://github.com/hazelcast/hazelcast-reference-manual/commit/1c7ae7c7d7ab7e150600540f9f2d82765e41cef6

**Comment by mdogan** [comment]
We are reverting the code. See https://github.com/hazelcast/hazelcast/pull/13846
