### ISSUE TITLE
REST cluster management samples need to be updated

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast-reference-manual#584]
Group name and password checks are at cluster REST calls removed from hazelcast codebase so we need to update existing samples:
https://github.com/hazelcast/hazelcast/pull/13757
https://docs.hazelcast.org/docs/3.10.5/manual/html-single/index.html#using-rest-api-for-cluster-management

`/nodes` and `/state` -->`GET` :
```
curl http://192.168.99.1:5701/hazelcast/rest/management/cluster/state
```
`/clusterShutdown`, `/memberShutdown`, `/hotBackup`, `/hotBackupInterrupt`, `/forceStart`, `/partialStart`:
```
curl -X POST -H "Content-Length: 0" http://10.216.1.42:5701/hazelcast/rest/management/cluster/memberShutdown
```

**Comment by Serdaro** [comment]
Milestone changed due to https://github.com/hazelcast/hazelcast/pull/13757
