### ISSUE TITLE
Configuring Ports

### ISSUE THREAD

**Issue by burakcelebi** [hazelcast/hazelcast-reference-manual#606]
For faster connections, we should recommend configuring ports alongside with hosts / IP address.

We should also give examples.

@pveentjer and @mmedenjak know about it.

Related: https://github.com/hazelcast/hazelcast-devops-guide/issues/57

**Comment by Serdaro** [comment]
@burakcelebi , Is there a related ticket/issue on this one? I'd like to examine a bit.
