### ISSUE TITLE
Cheatsheet for MapStore

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-reference-manual#607]
Individual IMap commands are documented in the Javadoc with their impact on MapStore -- `IMap.put()` triggers `store()`, `IMap.putTransient()` doesn't, etc...

What would be useful would be a single summary section

**Comment by Serdaro** [comment]
Resource: https://docs.hazelcast.org/docs/latest/javadoc/com/hazelcast/core/IMap.html

Draft of the output: https://docs.google.com/document/d/1wt7Hoq0Gnzczk_7QgR_4iwPqP3UBYikl2P5yLaIIfPw/edit
