### ISSUE TITLE
Rewrite the Discovering Native Clients section in IMDG Reference Manual

### ISSUE THREAD

**Issue by Serdaro** [hazelcast/hazelcast-reference-manual#611]
So that it will include discovery explanations not only for native clients but for all Hazelcast clients, including the client discovery in Hazelcast Cloud.

Here is the related Hazelcast Cloud content for the clients, to be enhanced and added:

Clients also can be used with cluster hosted by hazelcast. http://console.hazelcast.cloud
//Not sure how much we need to talk about Hazelcast Cloud. Is it okay to write  "http://console.hazelcast.cloud" explicitly?
After creating the cluster via web interface, you can create a cluster and get the related token.
This discovery token needs to be configured on the client, and REST should be enabled.
//Alternatively, the user can download hazelcast-client.xml form the web interface. Mention it?

```
ClientConfig config = new ClientConfig();
ClientNetworkConfig networkConfig = config.getNetworkConfig();
networkConfig.getCloudConfig().setDiscoveryToken("TOKEN").setEnabled(true);
networkConfig.setSSLConfig(new SSLConfig().setEnabled(true));
HazelcastInstance client = HazelcastClient.newHazelcastClient(config);
```

```
<network>
       <ssl enabled="true"/>
</network>
<properties>
        <property name="hazelcast.client.cloud.discovery.token">TOKEN</property>
 </properties>
```

It is advised to enable certificate revocation status JRE-wide, for security reasons.
You need to set the following system properties to true: 

* `com.sun.net.ssl.checkRevocation`
* `com.sun.security.enableCRLDP`

And you need to set the security property as follows:

`Security.setProperty("ocsp.enable", "true")`

More details can be found here:
http://docs.oracle.com/javase/6/docs/technotes/guides/security/jsse/JSSERefGuide.html#CERTPATH
http://docs.oracle.com/javase/6/docs/technotes/guides/security/certpath/CertPathProgGuide.html#AppC

**Comment by enesakar** [comment]
@Serdaro You can write directly to the hazelcast cloud docs site. I will fix and edit them.

**Comment by Serdaro** [comment]
This is done at the Hazelcast Cloud documentation on its own interface. Also, links to it have been given in the IMDG Reference Manual.
