### ISSUE TITLE
Clarifications needed for EP and PartitionAware sections.

### ISSUE THREAD

**Issue by Serdaro** [hazelcast/hazelcast-reference-manual#614]
https://docs.hazelcast.org/docs/3.11/manual/html-single/index.html#partitionaware:

* The code sample above the "Assume that you have a customers map where customerId is ..." line has `orders` map with key = `OrderKey`. But the code below this statement assumes `mapOrders` has `long` as keys. So they look disconnected.
* See `final class OrderKey implements PartitionAware, Serializable {`. There is a method named `long getOrderId()`. What is the purpose of this method? It is not used anywhere and all it does is cause confusion.
* See the big sample code under the statement `Here is an example code`. Objective of this code is to show how a task can be executed on servers. `OrderDeletionTask` implements PartitionAware but the description of this code does not explain how this PartitionAware will be used in this example, especially when the task is submitted through `executorService.submit(task)` and not `executorService.submitToKeyOwner(key, task)`. (why implement an interface instead of calling the right API?) Does this mean that PartitionAware comes in play automatically? If so, it should be documented as this is the section about PartitionAware and this code sample does not describe that properly

https://docs.hazelcast.org/docs/3.11/manual/html-single/index.html#entry-processor:

* I could not find a reason why `public Object process( Map.Entry<Integer, Integer> entry ) {` has to return something. Or, can the process method just return `null`? In the code sample, the `process` method returns the new value but the new value is updated inside the `process` method by explicitly calling `entry.setValue(...)`. It gets the value, increments it and returns the updated value. But to update the value, one has to explicitly call `entry.setValue`.  Why it should return it, since the incremented value is already being updated in the method. Is it mandatory to return the updated value in the method?

**Comment by ahmetmircik** [comment]
>docs.hazelcast.org/docs/3.11/manual/html-single/index.html#partitionaware:

I agree that we should fix the sample there.

>docs.hazelcast.org/docs/3.11/manual/html-single/index.html#entry-processor
Why it should return it, since the incremented value is already being updated in the method. Is it mandatory to return the updated value in the method?

Not required to return value, returning value makes caller aware from the latests values.
