### ISSUE TITLE
Standardize trustStore message across 3.11+ reference manual versions

### ISSUE THREAD

**Issue by jcaprice** [hazelcast/hazelcast-reference-manual#628]
In 3.11 we changed the behavior of Hazelcast when a trustStore is not explicitly configured. Our note in section [19.5.1, TLS/SSL for Hazelcast Members](https://docs.hazelcast.org/docs/latest/manual/html-single/index.html#tls-ssl-for-hazelcast-members), is updated in 3.11 and latest, but still has the old behavior documented in 3.11.1 and latest-dev:

3.11 and latest:

> If you configure TLS/SSL and do not specify the trustStore property, no default trusted certificates will be used; neither the keystore, nor the Java provided list of trusted CA certificates. Therefore, you ALWAYS need to configure the trustStore property.

3.11.1 and latest-dev:

> When you enable TLS/SSL and do not provide the trustStore property, the default trusted certificates are used, i.e., the Java provided list of trusted CA certificates.

Can 3.11.1 and latest-dev be updated to reflect the new change (like in 3.11 and latest)?

**Comment by Serdaro** [comment]
Thank you @jcaprice
