### ISSUE TITLE
Add filter example to Ringbuffer > Reading Batched Items

### ISSUE THREAD

**Issue by jcaprice** [hazelcast/hazelcast-reference-manual#629]
Add an example to section 7.7.12, Reading Batch Items, of the Hazelcast Reference Manual that shows the user how to implement the Hazelcast [IFunction interface](https://docs.hazelcast.org/docs/3.11/javadoc/com/hazelcast/core/IFunction.html) for the purpose of filtering RingBuffer entries when reading them in batches.

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/51f86e42bea6ca9be0f99a6ccd237c9ab646063f
