### ISSUE TITLE
Distributed Events missing registration examples in documentation 

### ISSUE THREAD

**Issue by dbrimley** [hazelcast/hazelcast-reference-manual#64]
Within the current documentation we have a few missing code samples for distributed events.

http://docs.hazelcast.org/docs/latest/manual/html-single/hazelcast-documentation.html#distributed-events

For example, MembershipListener docs show an interface implementation but there is no sample code of where or how to register this listener, there is no mention of this at all. The same is true for MigrationListener, PartitionLostListener, LifecycleListener and also MessageListener.

**Comment by Serdaro** [comment]
Thank you David, I am going to add this important missing information this week.

**Comment by Serdaro** [comment]
@dbrimley , I have updated the whole Distributed Events chapter. When you have time (preferably before the final release of 3.6), could you please have a look?

**Comment by Serdaro** [comment]
Sorry...The link: https://github.com/hazelcast/hazelcast-reference-manual/tree/master/src/DistributedEvents

**Comment by Serdaro** [comment]
Done.
