### ISSUE TITLE
Documentation about enterprise blue/green feature

### ISSUE THREAD

**Issue by sancar** [hazelcast/hazelcast-reference-manual#648]
This work has 3 prds. One from the management center. Two from client side work. 

https://hazelcast.atlassian.net/wiki/spaces/EN/pages/1213300753/Connection+Strategies+-+Blue+Green+by+way+of+Client+Configuration+Design
https://hazelcast.atlassian.net/wiki/spaces/EN/pages/1199407524/Connection+Strategies+-+Blue+Green+by+way+of+CNAME+Configuration+Design
https://hazelcast.atlassian.net/wiki/spaces/EN/pages/1454309714/MC+Black+White+List+Clients+-+TDD

**Comment by Serdaro** [comment]
See https://github.com/hazelcast/hazelcast-reference-manual/blob/master/src/docs/asciidoc/hazelcast_clients.adoc#blue-green-deployment-and-disaster-recovery

**Comment by Serdaro** [comment]
Fixed with the above commit and pushes afterwards..
