### ISSUE TITLE
max-idle-seconds < 2 is not possible 

### ISSUE THREAD

**Issue by yozank** [hazelcast/hazelcast-reference-manual#670]
As part of [pull/13320](https://github.com/hazelcast/hazelcast/pull/13320), we don't support 1-second `max-idle-seconds` any more. In return, the max-idle-seconds range is increased from 25 days to ~70 years. 

We should add this information to the documentation of `max-idle-seconds` property. 

The following is detailed clarification from @tkountis at [14697](https://github.com/hazelcast/hazelcast/issues/14697#issuecomment-472785324): 

```
Due to the loss of millisecond resolution on the Record timestamps (LUT, LAT, LST etc) when you
 create a record at time=1s (no MS info), and access it at wall-clock time 1.1 (includes 100ms) and
 then at wall-clock time 1.4 (includes 400ms) the timestamps get updated only with the second part 
of the wall-clock time, i.e., 1s (no MS info, again). In other words, it behaves as if the record was not
 touched.

Therefore, setting a max-idle to 1second will expire the record after 1 second, regardless of 
operations done on that same record in-between.
```

**Comment by Serdaro** [comment]
@yozank , currently we are saying that "Its default value is "0", meaning Integer.MAX_VALUE". Should it stay like this?

**Comment by yozank** [comment]
@Serdaro yes, I missed that, it is still a valid statement. Actually, the only problem is with 1-second setting.
