### ISSUE TITLE
WAN tries to deserialize user objects on target cluster - user should place jars

### ISSUE THREAD

**Issue by sertugkaya** [hazelcast/hazelcast-reference-manual#702]
As a customer question and a discussion with @mmedenjak ; Wan replication tries to deserialize user object on receiving side, which can cause a serialization exception if object is not known. This is something we'll address in the upcoming 4.0 version so that while using binary memory format for your map objects, no serialization will be done, hence you'll not need the object on the classpath on target cluster.

So placing jars on the classpath is the recommended approach for now, we should document this as I couldn't see it there.

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/52c06588f716a22c7b7f23942efd1fc0d8f672b0
