### ISSUE TITLE
PartitioningStrategy is not supportted by clients 

### ISSUE THREAD

**Issue by yozank** [hazelcast/hazelcast-reference-manual#710]
[PartitioningStrategy](https://docs.hazelcast.org/docs/3.12.1/manual/html-single/index.html#partitioningstrategy) allows related data to be stored together by placing entries according to the provided partition key.

It is supported by member side in **per map** and **per member** flavors. However, clients don't support it yet. 

Implementing PartitioningStrategy for a map at the member side and accessing/mutating the same map from client-side causes data inconsistencies. 

Since member side has PartitioningStrategy definition and clients don't, entries added by members will end up in different partitions than entries added by clients. 

We don't issue any error or warning if clients access the maps that have PartitioningStrategy configuration by member side. 

We should clarify on the documentation that PartitioningStrategy for clients are not supported yet and clients should not access the maps with PartitionStrategy definition at the member side.

**Comment by burakcelebi** [comment]
Related: https://github.com/hazelcast/hazelcast/issues/13950
