### ISSUE TITLE
IndexAwarePredicate

### ISSUE THREAD

**Issue by burakcelebi** [hazelcast/hazelcast-reference-manual#711]
The reference manual does not mention com.hazelcast.query.IndexAwarePredicate. Custom predicates need to implement IndexAwarePredicate if the user wants to add an index.

**Comment by mmedenjak** [comment]
Since 4.0, IndexAwarePredicate is no longer public - https://github.com/hazelcast/hazelcast/pull/15142

**Comment by burakcelebi** [comment]
Thanks @mmedenjak!
