### ISSUE TITLE
Remove references to Hazelcast MapReduce in manual 

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast-reference-manual#794]
Hazelcast MapReduce is being removed completely. All references in references manual and code should be removed: https://docs.hazelcast.org/docs/latest-dev/manual/html-single/index.html#moving-mapreduce-tasks-to-hazelcast-jet

**Comment by Serdaro** [comment]
@Holmistr , the whole section on this (11.7 MapReduce Depreciation and Removal) talks about the motivation and replacement of the MapReduce feature removal, which is removed in 4.0. So, in my opinion, it is informative to talk about this in the 4.0 manual (which is the version in question for MapReduce removal). Maybe it is better to delete the whole MapReduce removal content in 4.1?

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/bae9934b6d6ed0ecb1c3cd8ab2a5a98a71b73f7a
