### ISSUE TITLE
WAN replication improvements

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast-reference-manual#798]
I'm currently trying to setup WAN replication with the help of our manual. Simple Active-Passive setup, two instances, just get it running ASAP locally. And I'm failing to do this in 10 minutes.

My biggest concern is that refmanual tends to go deep right from the beginning describing all the options, configurations etc. before actually showing how to set it up. The closest snippet to this (which actually contains extra brackets) is https://docs.hazelcast.org/docs/latest-dev/manual/html-single/index.html#configuring-wan-replication-for-imap-and-icache , which is several sections, paragraphs after the start of the WAN replication. But even with this code snippet, I'm not sure what I do next. 

I would suggest to show a code snippet (complete one) right from the beginning and then go into details afterwards. Otherwise, it's really hard for a newcomer like me to understand what he's doing.

I'm happy to assist @Serdaro with brainstorming, even drafts of the text and reviews.

**Comment by mmedenjak** [comment]
Some comments from @blazember :

```
Ref manual
- It says EE only. We have OS support. There could be a short section added explaining the differences and building blocks.
- Emphasize that HZ WAN replication is asynchronous and makes the participant clusters only eventually consistent (and not strongly eventually consistent - think of merge policies).
- Probably a helicopter-view explanation of how our EE WAN replication works fits here.
- Also mention that only IMap and ICache is supported by replication.
- Active-Passive vs Active-Active: Needs better description and example. I believe for Active-Passive failover is not a good example since after a failover the clusters' roles need to change and the previously Passive cluster takes over the "ownership" and the replication direction needs to turn the opposite way. This could lead the question SAP asked that do they need to reconfigure the cluster in case of a failover?
A better example for Active-Passive replication might be a cross-site master->replica replication where the master cluster replicates the changes to separate distant clusters. A concrete example distributing user-specific pricing profile in trading to regional trading venues. 
- Simplify configuration examples:
 1. Start with a dead-simple examples both for active-passive and active-active setups with statis endpoints.
 2. Add endpoint discovery
 3. Fine tuning options (ack types, coalescing, batch size, etc) with adding what to consider where possible (trade-offs).
- Maybe keep a section in the end of the configuration part with all options to have everything in one place with links to sections discusses the options in detail.
- Remove mentioning of WanNoDelayReplication in 4.0 docs.
- Synchronization
 - "Synchronizing WAN Target Cluster" was written only with FULL synchronization in mind, since then we have Delta sync as well. 
 - Lacks the connection between FULL and Delta sync.
 - Move Full and Delta synchronization under a WAN synchronization section. 
- Lack of explanation of WAN topologies, in particular that event loops are prevented. 
- Add that evictions are not synchronized and why is that
```

**Comment by mmedenjak** [comment]
Also, regarding the state of the documentation as of Feb 3, I'd shorten the introduction part a bit, fix the wording and also add more information to the REST API section since it doesn't include all of the REST endpoints and it is a bit outdated.

**Comment by Serdaro** [comment]
Following notes from Jiri&Serdar meeting to be applied after Matko's works:

- [ ] Change 23. chapter name: WAN -> WAN Replication

- [ ] Defining WAN Replication: Change the heading text to "WAN Replication Types"

- [ ] Defining WAN Replication: Right after the active-active, active-passive bulleted list, open subsections “Setting up active-active/active-passive WAN Replication” sections: Give the minimal configuration for each, include the map stuff (wan-replication-ref). Explain these minimal configurations. Also, give use cases for those active-active/active-passive bulleted lists.
  - Here, also provide content about `wan-replication-ref`
- [ ]  Include `custom-publisher` and `consumer` as separate sections under WAN Publisher Replication Implementation section, as they are advanced topics.
- [ ] Defining WAN Replication Using Discovery SPI: Only talk about the `discovery-strategy` element. Give optional/mandatory info with the minimal configuration. And give information about the optional ones.
- [ ] Open up an "Advanced Features" section and include the WAN sync, Dynamic stuff, Event filtering API in it.
- [ ] After "Advanced Features", open up an "Advanced Configuration" section and put the previous 23.1.4, 5, 6, 7, 8, 9, 10 under it. (I guess this is covered as "Tuning WAN Replication" section)..
- [ ] Make `target-endpoints` element explanation as a new section like under this new "Advanced Configuration" section.
- [ ] Provide use cases for those `batch-size`, `batch-maximum-delay`, etc.: Why should we use them?
- [ ] Queue Full Behavior: talk with Matko; describe how do we know the queue is full..
- [ ] Event Filtering API, Ack Types sections: Remove obsolete info like "Starting with 3.6"...
- [ ] Dynamically Adding WAN Publishers: Provide content on why and how to do it.
- [ ] WAN Replication Additional Information: The content of it should be in the minimal basic configuration part (the beginning of the whole chapter). 2nd paragraph should go into the Failure & Recovery section. 3rd paragraph should be removed.
- [ ] Delta WAN Sync: Make it same level as the Failure & Detection section (This has been covered)
- [ ] Using Delta WAN Sync: the intro numbered list needs a code snippet; it is there somewhere, so rearrange the configuration snippet, remove `wan-replication-ref` from it.
- [ ] Configuring Delta WAN Sync: Provide a complete configuration snippet; just merge Using and Configuring sections.
- [ ] REST API: Should go under "The Process". (This has been covered up by making it more visible).
- [ ] Statistics: Level it up. (This has been covered)

**Comment by Serdaro** [comment]
@Holmistr , @mmedenjak , @blazember : This week I will be working on the above notes, along with Zoltan's comments.

**Comment by Serdaro** [comment]
@Holmistr , @mmedenjak @blazember : you can track the progress in the output here: https://docs.hazelcast.org/docs/Test/#wan-replication

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/pull/821
