### ISSUE TITLE
Document MapLoader lifecycle

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast-reference-manual#810]
The reference manual does not talk lifecycle of MapLoader. There is a paragraph talking about the `MapLoaderLifecycleSupport` interface, but it's in the "Storing Entries to Multiple Maps" chapter where it does not belong. 

![image](https://user-images.githubusercontent.com/158619/73088906-792a6880-3ed5-11ea-9e0b-7003eafab0d5.png)

This deserves its own section, before the "Storing Entries to Multiple Maps"

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/pull/815
