### ISSUE TITLE
Remove executor pool size from the reference manual 

### ISSUE THREAD

**Issue by sancar** [hazelcast/hazelcast-reference-manual#813]
This config was removed in 4.0. It is forgotten to be removed and mentioned in migration guide. 

 https://docs.hazelcast.org/docs/latest/manual/html-single/#executorpoolsize

**Comment by Serdaro** [comment]
Mentioned in the release notes. Its content now removed. 4.0 and latest-dev Reference Manuals have been updated and uploaded. Thanks Sancar.

(https://github.com/hazelcast/hazelcast-reference-manual/commit/76533c10117a8f7a68be915176da0ac449f21cd6)
