### ISSUE TITLE
Leftovers in Hazelcast 4.0 reference manual

### ISSUE THREAD

**Issue by tomaszszewczyk-silvair** [hazelcast/hazelcast-reference-manual#814]
There are some out-of-date snippets in reference manual. For example: [Supported Configurations with hazelcast Namespace](https://docs.hazelcast.org/docs/latest/manual/html-single/#supported-configurations-with-strong-hazelcast-strong-namespace). There is `<hz:cluster>` tag in the snippet, which is not existent anymore.

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/6c18efbba1d26abbc9330a34afc055bc97b52687
