### ISSUE TITLE
Guarantees

### ISSUE THREAD

**Issue by burakcelebi** [hazelcast/hazelcast-reference-manual#816]
Please see the comment below from a developer:

> The fact I have to dig through your site (5 minutes, still can't find it) to learn about the guarantees indicates it's not really worth uprooting Redis out of my common toolbox.

Maybe a new item might be added to the FAQ section.

**Comment by Serdaro** [comment]
@burakcelebi , I couldn't get on what we should we provide in terms of guarantees. Which  aspects should be mentioned there?

**Comment by burakcelebi** [comment]
@Serdaro I think it might be nice to mention data consistency, durability, and availability.
