### ISSUE TITLE
Java specific items in Hazelcast’s Distinctive Strengths

### ISSUE THREAD

**Issue by burakcelebi** [hazelcast/hazelcast-reference-manual#817]
Please see the comments from a developer about the **Hazelcast’s Distinctive Strengths** subsection. We should consider updating there so that it becomes meaningful to non-java people too.

> Hazelcast is only a JAR file. You do not need to install software.

_Yes you do. You have to install Java, at the very least._

> Hazelcast is a library, it does not impose an architecture on Hazelcast users.

_This makes literally no sense. Is it a data store or is it a client?_

**Comment by Serdaro** [comment]
I have been going through the whole Hazelcast Overview chapter, so it is going to be updated soon.

**Comment by Serdaro** [comment]
@burakcelebi , could you please have a look the above commit?

**Comment by burakcelebi** [comment]
Awesome, many thanks @Serdaro! :)

**Comment by Serdaro** [comment]
Fixed with the above comment.
