### ISSUE TITLE
(hazelcast-client-failover) try-count and connection-attempt-limit confusion 

### ISSUE THREAD

**Issue by yozank** [hazelcast/hazelcast-reference-manual#818]
There are reports that when the fail-over is configured, the clients will only take this `try-count` value for reconnection attempts. 

For example, `try-count` for fail-over is 4 and `connection-attempt-limit` is 100 and there are 2 clusters. 
The maximum number of connection attempts would be 4 * 100 * 2 = 800. 

We should explicitly state that `try-count` of `hazelcast-client-failover` only means the number of iterations on the fail-over configuration list. 
For each cluster in the list, `connection-attempt-limit` or Client connection strategy configuration is still considered.

**Comment by Serdaro** [comment]
Closing with the above commits.
