### ISSUE TITLE
PartitionStrategy for the client comment fix

### ISSUE THREAD

**Issue by sancar** [hazelcast/hazelcast-reference-manual#830]
https://docs.hazelcast.org/docs/4.0/manual/html-single/index.html#partitioningstrategy
The warning at the end says that client does not have partitions strategy configuration at all. 

Client does have global partition strategy (which is configured via property). 
Client does not have partition strategy per map (yet).  Plan is to add it.

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/334f7ce5b7bad6e77671c938680c1ff2bd88ebe6
