### ISSUE TITLE
New Feature GenericRecord/GenericRecord/Builder

### ISSUE THREAD

**Issue by sancar** [hazelcast/hazelcast-reference-manual#859]
Related PRD https://hazelcast.atlassian.net/wiki/spaces/EN/pages/2369421494/Portables+without+Domain+Object+Design+Document?focusedCommentId=2557706334#comment-2557706334
Related TDD https://hazelcast.atlassian.net/wiki/spaces/EN/pages/2369421494/Portables+without+Domain+Object+Design+Document
Related PR https://github.com/hazelcast/hazelcast/pull/17105
Note that the work also includes performance improvements on query with Portable which could be a good idea to mention in release notes. 
Related code samples: https://github.com/hazelcast/hazelcast-code-samples/pull/443

Here is the draft documentation:

@Beta GenericRecord / GenericRecord.Builder

A generic object interface that is returned to the user when the domain class is missing on the classpath.
More specifically, for Portable, if PortableFactory is not given in the SerializationConfig
see  SerializationConfig.addPortableFactory/addPortableFactoryClass, since the user domain class 
can not be created, we will return GenericRecord instead. 
Note that before 4.1, in the same situation we were throwing HazelcastSerializationException("Could not create Portable for class-id: " + classId)

GenericRecord is an immutable object. It allows you to read the fields of objects via related read fields. 

One use-case where this will be powerful is that client/server architecture where the cluster does not have the domain classes of the clients.  On remote calls like distributed executor service or EntryProcessors, you may need to access to the domain object. In
case the class of the domain object is not available on the cluster, GenericRecord allows to access, read and write the objects
back without the class of the domain object on the classpath. Here is a `read` example with EntryProcessor:
```
    map.executeOnKey(key, (EntryProcessor<Object, Object, Object>) entry -> {
             Object value = entry.getValue();
             GenericRecord genericRecord = (GenericRecord) value;

             int id = genericRecord.readInt("id");

             return null;
         });
```

An alternative approach before 4.1 was to use UserCodeDeployment to deploy the classes from the client to the cluster.
It has a couple of restrictions. One is that if you want to use Portable Versioning support, you can not upload
a new version of your class to the cluster. Loading two different versions of the same class on the JVM is not a problem that we want to solve. In a GenericRecord approach, you can easily write different versions of your classes
from the clients, and access them via GenericRecord interface without using UserCodeDeployment. 

With the introduction of GenericRecord, UserCodeDeployment should be used only for functional objects like Runnable,
Callable, EntryProcessors, etc.  

You can also create a GenericRecord in Portable format with GenericRecord.Builder as follows:

```
ClassDefinition classDefinition = new ClassDefinitionBuilder(PORTABLE_FACTORY_ID, EMPLOYEE_CLASS_ID)
                        .addUTFField("name").addIntField("id").build();
        
GenericRecord namedRecord = GenericRecord.Builder.portable(classDefinition)
                .writeUTF("name", "foo")
                .writeInt("id", 123).build();
```
Note that class definitions are better to be created once and used when creating different instances of same type GenericRecord.

We have also added two convenience methods on GenericRecord for you to avoid passing a class definition. 
For example, on EntryProcessors if you want to modify a value and put it back, you don't need to create a class definition.
Instead you can create a builder from GenericRecord which carries the same class definition as follows:

```
map.executeOnKey("key", (EntryProcessor<Object, Object, Object>) entry -> {
            GenericRecord genericRecord = (GenericRecord) entry.getValue();
            GenericRecord modifiedGenericRecord = genericRecord.newBuilder()
                    .writeUTF("name","Kermit")
                    .writeLong("id", 4)
                    .writeInt("age",20)
                    .writeUTF("surname", "The Frog").build();
            entry.setValue(modifiedGenericRecord);
            return null;
        });
```

Another convenience method is `cloneWithBuilder`. This is usefull if you will update only a couple of fields
from original genericRecord. In that case new builder carries both classDefinition and values from the original
genericRecord. Here is the same example where we just update the age:

```
map.executeOnKey("key", (EntryProcessor<Object, Object, Object>) entry -> {
            GenericRecord genericRecord = (GenericRecord) entry.getValue();
            GenericRecord modifiedGenericRecord = genericRecord.cloneWithBuilder()
                    .writeInt("age",22).build();
            entry.setValue(modifiedGenericRecord);
            return null;
        });
```

A second use-case is on the client-side(could also be a member).
GenericRecord allows to read from/write to a cluster without having the related classes on the classpath
A client could work with the cluster without introducing the PortableFactory at the start.
In this case, the client will work with `GenericRecord`s instead of domain classes.
For example, a client code with the map will look like following:
```
        GenericRecord record = (GenericRecord) map.get("key1");
        String name = record.readUTF("name");
        int id = record.readInt("id");
        
        GenericRecord newGenericRecord = genericRecord.cloneWithBuilder()
                .writeInt("age",22).build();
        
        map.put("key2", newGenericRecord);
```

**Comment by Serdaro** [comment]
@sancar , https://github.com/hazelcast/hazelcast-reference-manual/commit/96ffcc72dfe9bf663a765fc108025191f3bb3fd6

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/96ffcc72dfe9bf663a765fc108025191f3bb3fd6
