### ISSUE TITLE
Hazelcast IMDG 4.0.3 Reference Manual (14.2.2. Example JCache Application)

### ISSUE THREAD

**Issue by NickGol** [hazelcast/hazelcast-reference-manual#887]
In chapter "14.2.2. Example JCache Application".
It seems to me that there is a mistake in explanation of  **CachingProvider cachingProvider = Caching.getCachingProvider();**

First of all, we retrieve the **javax.cache.spi.CachingProvider** using the static method from **javax.cache.Caching.getCachingManager()**, which automatically picks up Hazelcast as the underlying JCache implementation, if available in the classpath.

Maybe it's better to write javax.cache.Caching.getCachingProvider() instead of javax.cache.Caching.getCachingManager().

**Comment by Serdaro** [comment]
Thanks a lot @NickGol .
@vbekiaris , do you have any comments on this?
