### ISSUE TITLE
Need to update documentation related to PARTITION_OPERATION_THREAD_COUNT(hazelcast.operation.thread.count) property

### ISSUE THREAD

**Issue by dineshbhagat** [hazelcast/hazelcast-reference-manual#899]
I am upgrading Hazelcast from 3.x to 4.x, have doubt about one property **PARTITION_OPERATION_THREAD_COUNT**  
According to [this](https://docs.hazelcast.org/docs/latest/manual/html-single/#system-properties) (**hazelcast.operation.thread.count**) documentation,   
"Number of partition based operation handler threads. -1 means CPU core count.",   
but when I checked 4.x, the default is `Math.max(2, RuntimeAvailableProcessors.get())`  

Hopefully, the following is not an issue with 4.x, [Ref](https://docs.hazelcast.org/docs/latest/manual/html-single/#movingcopying-hot-restart-data)
`Unfortunately having a different number of CPU cores is not that straightforward. Hazelcast partition threads, by default, uses a heuristic from the number of cores, e.g., # of partition threads = # of CPU cores. When a Hazelcast member is started on a server with a different CPU core count, number of Hazelcast partition threads changes and that makes Hot Restart fail during the startup. Solution is to explicitly set number of Hazelcast partition threads (hazelcast.operation.thread.count system property) and Hot Restart parallelism configuration and use the same parameters on the new server. For setting system properties see the System Properties appendix.`
[3.x](https://github.com/hazelcast/hazelcast/blob/3.12.z/hazelcast/src/main/java/com/hazelcast/spi/properties/GroupProperty.java#L75-L76) branch, [master](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/spi/properties/ClusterProperty.java#L1318-L1320) branch

Ref: https://hazelcastcommunity.slack.com/archives/C015Q2TUBKL/p1605861431008000

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/f54720dfbdd7ffc21ffcc4f0759025cc4be8522b, thanks a lot @dineshbhagat!
