### ISSUE TITLE
Executing a simulator tests

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast-reference-manual#9]
There are some isuses with this content:
- HZ Reference Manual: provisioner logging is for 0.3
- there is a reference to run.sh; but it is totally unclear what the content should be.

Documentation needs to be followed step by step and fixed at every point where a user can run into a problem.

By @pveentjer via https://github.com/hazelcast/hazelcast-simulator/issues/659.

**Comment by Serdaro** [comment]
Content enhanced by @Donnerbart . In addition, the whole content moved to Simulator's own repo.
