### ISSUE TITLE
Update JCache doc & examples

### ISSUE THREAD

**Issue by vbekiaris** [hazelcast/hazelcast-reference-manual#903]
- There are still places in reference manual which use `Caching.getCachingProvider()` implying a member-side caching provider is returned, however since 4.0 this returns by default a client-side provider.
- Clarify member- and client-side `CachingProvider`s cannot be mixed with client-/member-side `HazelcastInstance`s respectively, when binding to an existing `HazelcastInstance`.
- Using a `URI` as instance name is no longer supported as a means to bind to a named instance since https://github.com/hazelcast/hazelcast/pull/15995 was merged. The related section should be removed from reference manual.

Related to https://github.com/hazelcast/hazelcast/issues/17900

**Comment by Serdaro** [comment]
Fixed with #907
