### ISSUE TITLE
Please add an explicit license file to the repo

### ISSUE THREAD

**Issue by mbrukman** [hazelcast/hazelcast-reference-manual#92]
Could you please add an explicit LICENSE file to the repo so that it's clear under what terms the content is provided, and under what terms user contributions are licensed?

Per [GitHub docs on licensing](https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license):

> Generally speaking, the absence of a license means that the default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work. This might not be what you intend.

For example, [Creative Commons Attribution 4.0 International](https://creativecommons.org/licenses/by/4.0/) (aka _CC BY 4.0_), could be a good choice here since the content is text, not code.

Thanks!

**Comment by Serdaro** [comment]
Thank you, let me discuss this with the team.

**Comment by gregrluck** [comment]
Previously the documentation was a directory in the main Hazelcast repo which has an Apache 2 license. 

The intention is for the docs to be open source as well. Will check with legal what the appropriate license is.

**Comment by Serdaro** [comment]
Added the license file to the repo: https://github.com/hazelcast/hazelcast-reference-manual/commit/3b26cdc12646e4e2a5fdf61e74d8090a58397736
