### ISSUE TITLE
Bullet points wrong identation

### ISSUE THREAD

**Issue by pmverma** [hazelcast/hazelcast-reference-manual#922]
It is confusing to read with an incorrect header-like-bullet.

![image](https://user-images.githubusercontent.com/5289123/128176523-f59e163e-56ef-42d1-9d4d-bc0aebf71002.png)

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hz-docs/pull/91/files#diff-a3730be3593a869e467c453797757fe5429c4ae72b757bb6275254857333428eR404

Thank you @pmverma
