### ISSUE TITLE
Single HTML is scrollable sideways

### ISSUE THREAD

**Issue by muratayan** [hazelcast/hazelcast-reference-manual#97]
Only tried with Chrome. It's in 3.6-EA2, didn't try other versions. It is causing some problems. 

<img width="1242" alt="screen shot 2015-12-17 at 20 31 09" src="https://cloud.githubusercontent.com/assets/4989547/11878254/4687d604-a4fd-11e5-9fb2-bbe73b748ac8.png">

**Comment by Serdaro** [comment]
Thank you Murat. Let me check.

**Comment by Serdaro** [comment]
Solved after using the new generator tool. Please check http://docs.hazelcast.org/docs/latest-development/manual/html/index.html
