### ISSUE TITLE
Dead link on Simulator page

### ISSUE THREAD

**Issue by mtopolnik** [hazelcast/hazelcast-reference-manual#98]
"Hazelcast Simulator is available as a downloadable package on the Hazelcast web site. Please refer to the Installing Simulator section for more information." 

http://docs.hazelcast.org/docs/3.5/manual/html/simulatoroverview.html#installing-simulator

"Installing Simulator section" is a dead link.

**Comment by Serdaro** [comment]
@mtopolnik , none of the cross-references in the Multi-HTML version are working. We will remove this version in a couple of weeks.

**Comment by Serdaro** [comment]
Closing since there is no more Multi-HTML version.
